### ISSUE TITLE
Extended tracking

### ISSUE THREAD

**Issue by jgwinner** [artoolkitx/artoolkitx#1]
##### Description:

Hello! Thank you guys for taking this on. I have a question:

Is it possible to do 'extended tracking' meaning:

1) Scan a marker
2) Display some content 'behind' the user or around them.
3) User turns to look at the Augmented content, tracking continues.

I'm looking for something similar to this:

[https://samples.argonjs.io/directionswebgl/](https://samples.argonjs.io/directionswebgl/) 

with the wrinkle that in my code, instead of "North" etc. there would be arrows; the arrows would direct users to other locations based on the marker that had been scanned. 

Mostly I need ground plane detection, but the environment is really busy with people walking around, so I've found with commercial libraries, the Augmented objects disappear due to tracking being lost. The advantage of the simpler ArgonJS example, is the items still stay on screen. 

If Gyro/IMU tracking could be added to make augmentations persist, that's really what most people want. Full SLAM would be nice, but this could be an intermediate step.

Thank you,

== John ==

**Comment by ThorstenBux** [comment]
You can scan a marker and have the 3D model placed behind the user. However, when the tracking of the marker is lost the content is not rendered anymore. This can be changed in a way the 3D model stays in place when the marker tracking is lost. But that means that there is not tracking anymore and the 3D model just floats in space. I believe you could do something like this by combining ARCore/ARKit with artoolkitX. Scan a marker to get the scene you want but use ground/plane recognition for tracking.
