### ISSUE TITLE
small issues

### ISSUE THREAD

**Issue by dy-dev** [artoolkitx/artoolkitx#10]
Hello 

It seems there is a slight error in the file ARTrackerNFT.cpp at line 227
if ( **!**trackingThreadHandle) => should be if ( trackingThreadHandle) 
otherwise tracking of the nft marker is never done.

Moreover I've encountered a very strange issue in ARController.cpp in the function int ARController::addTrackable(const std::string& cfgs)
In the artoolkitx_2d_tracking_example project, when calling the addtrackable function, the string is noted as "unreadable" in the dll or empty, whereas the same function called the same way in artoolkitx_squared_tracking_example has no problem whatsoever.
I have not been able to figure out why but to work around the project I have created a function that takes the adress of the buffer of the string as a uintptr_t that I access as a char * in the dll, and that does the trick. 
Any idea of what the problem could or the test I could do to help you find what is going on?
Thank you

**Comment by philip-lamb** [comment]
OK, first issue is fixed in https://github.com/artoolkitx/artoolkitx/commit/05bc37a5ea13a106c8d7f5ee7dfef9a6369113b5. I'll look into the second.

**Comment by dy-dev** [comment]
whoua that was quick

**Comment by philip-lamb** [comment]
What compiler? It's possible the string is being optimised out. I'm not seeing this behaviour on Xcode on macOS.

**Comment by dy-dev** [comment]
Sorry I should have given you that on the first comment : 
I'm using visual studio community 2017 on a windows 10 machine

**Comment by dy-dev** [comment]
in the main : 
markerIDs[i] = arController->addTrackableAdress( markerConfig );
![capture1](https://user-images.githubusercontent.com/9073804/38859300-ffc76736-422d-11e8-82f8-fc8d999c26f2.PNG)

in the arcontroller.cpp
![capture2](https://user-images.githubusercontent.com/9073804/38859367-2718762c-422e-11e8-9157-63c1f40ec3a1.PNG)

In the allocator, _MyVal2 _bx, the address of _Buf seems to shift 8bits but I don't understand why it would do that. And it is not a rights restriction memory problem between exe and dll because I can access freely the information with the memory adress

**Comment by philip-lamb** [comment]
@dy-dev Did you resolve this issue? I'll close this in a few days if no feedback.

**Comment by LionisIAm** [comment]
<troll> few days latter </troll>

**Comment by philip-lamb** [comment]
I really ought to set reminders on these things. Closing this with just a note that weird string behaviour on windows between an exe and a dll can be when one is built with the debug runtime, and one with the release runtime.
