### ISSUE TITLE
FlipV/FlipH Inverted?

### ISSUE THREAD

**Issue by OptrixAU** [artoolkitx/artoolkitx#100]
Has the meaning of 'flip vertical' and 'flip horizontal' changed for both ARToolkitX and ARUnityX?

Normally, I'd expect the 'FlipV' video option to mirror my image around the vertical axis (ie. flip the sides of my face around if the camera was looking directly at me, not flip me upside down).

Instead, FlipV seems to flip along the _horizontal_ axis, and FlipH appears to flip along the _vertical_ axis. 

This appears the opposite of the settings in ARToolkit5. 

Is this a deliberate change? Note that the change is also consistent in ARUnityX - the 'horizontal' and 'vertical' camera flipping also follows ARToolkitXs naming. In this case I'll assume its taking its lead from the ARToolkitX library.

**Comment by philip-lamb** [comment]
You're correct in that the "V" or "H" referred to in the flip is not the axis of symmetry, but the axis in which the effect is observed. This seemed at the time to be a fit for user intent: "Hey my image is upside-down, I need to flip it vertically!" ... hope the explanation helps :-)
