### ISSUE TITLE
Convert to screen coordinate

### ISSUE THREAD

**Issue by huyhoangk50** [artoolkitx/artoolkitx#101]
I am using arcontroller->findTrackable to find the maker. And it return maker information with some matrix like trans, transformationMatrix, transformationMatrixX. It is the camera coordinate, right? How can I convert it to screen coordinate to show in the stream. Thanks in advance.

**Comment by ThorstenBux** [comment]
The way to do is to use a 3D library and add 3D models to the stream using the transformationMatrix.

**Comment by huyhoangk50** [comment]
@ThorstenBux I just want to get the position of marker in screen. (x, y in pixel and the marker direction (top, bottom, left, right))

**Comment by ThorstenBux** [comment]
Yep, I'm familiar with libraries to return 2D screen coordinates. Recent face landmark recognition libraries are doing just that. I've never attempted to do something like that we artoolkitX and I actually think a big benefit of artoolkitX is that it returns real 3D coordinates which also gives you the correct perspective of your 3D model in the scene.

**Comment by philip-lamb** [comment]
If you're using square markers (template or barcode) and want to know the 2D coordinates in the source video image where the corners of the square were found by the square tracker, at the moment this information is not exposed in the C++ interface, but it's store in the ARMarkerInfo structure which is used by ARTrackableSquare to update trackable info, so you could modify the source and do something with this info yourself. See http://www.artoolkitx.org/artoolkitx/Documentation/APIReference/ARX/html/struct_a_r_marker_info.html#a45fa4dddc7e6edecb1de6f1bb973e9a4

In general though, if you've got a marker pose (and this also applies to the texture markers) you can get the screen coordinates by projecting the 3D coordinate. Basically, multiply by the modelview, projection, and viewport matrices, in that order.
