### ISSUE TITLE
Rendering data on Computer rather than mobile device

### ISSUE THREAD

**Issue by vaibhavchincholkar** [artoolkitx/artoolkitx#102]
I am a student and working on my academic project.
I want to run the OpenGL rendering part on the computer (Edge device) and send the data/frames from computer to android device and show the 3d object on the detected trackable. 
I am planning to send Projectionmatrix and model-view matrix from the mobile device to the computer. Multiply the matrices with the object and render the object and send it to the mobile device. 
I have a few questions if anyone could answer
1. what should I send from computer to mobile device like buffer data, image frames or is there anything better?
2. how should I render sent data on the mobile device? as with OpenGL, we have drawpixel() , OpenGL ES doesn't have.
Is there any way I could achieve this?

**Comment by philip-lamb** [comment]
This is a general question about AR application design, and needs to be made more specific to be able to be addressed.
