### ISSUE TITLE
Multiple NFT marker

### ISSUE THREAD

**Issue by SystemDiagnosticss** [artoolkitx/artoolkitx#103]
Hello. Is it possible work with multiple NFT-marker in current version library?

**Comment by philip-lamb** [comment]
Yes. Both the NFT and AR2 trackers allow both multiple images, and potentially multiple simultaneous image tracking.

If you are using the ARToolKit v5-style NFT markers, then to enable more than one marker to be tracked simultaneously, you need to enable nftMultiMode, either by calling `arwSetTrackerOptionBool(ARW_TRACKER_OPTION_NFT_MULTIMODE, true)` if you're using the C interface, or `getNFTTracker()->setNFTMultiMode(true)` if you're using the ARController C++ class directly.

For the AR2 tracker, multiple simultaneous tracking is always on.

**Comment by kalwalt** [comment]
Hi @philip-lamb there is also a similar setup in Artoolkit5 for enabling multi NFT markers?
Thank you.
