### ISSUE TITLE
cc1: error: unknown value ‘core2’ for -march

### ISSUE THREAD

**Issue by xjiao004** [artoolkitx/artoolkitx#105]
I compiled artoolkitx sdk on rk3399, but it encountered this problem above. Anyone konws where  should I fix?

**Comment by xjiao004** [comment]
cc1: error: unknown value ‘core2’ for -march
ARX/AR2/CMakeFiles/AR2.dir/build.make:110: recipe for target 'ARX/AR2/CMakeFiles/AR2.dir/featureSet.c.o' failed
make[2]: *** [ARX/AR2/CMakeFiles/AR2.dir/featureSet.c.o] Error 1
CMakeFiles/Makefile2:492: recipe for target 'ARX/AR2/CMakeFiles/AR2.dir/all' failed
make[1]: *** [ARX/AR2/CMakeFiles/AR2.dir/all] Error 2
cc1: error: unknown value ‘core2’ for -march
depends/common/src/Eden/CMakeFiles/Eden.dir/build.make:134: recipe for target 'depends/common/src/Eden/CMakeFiles/Eden.dir/EdenTime.c.o' failed
make[2]: *** [depends/common/src/Eden/CMakeFiles/Eden.dir/EdenTime.c.o] Error 1
CMakeFiles/Makefile2:711: recipe for target 'depends/common/src/Eden/CMakeFiles/Eden.dir/all' failed
make[1]: *** [depends/common/src/Eden/CMakeFiles/Eden.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Here is my errors! Anyone knows the solution pls help me! Really appreciate your assistant!

**Comment by philip-lamb** [comment]
A quick search tells me rk3399 is ARM 64-bit architecture, but it looks like you're using the standard Linux build which assumes x86 architecture.

Since this is a custom platform, you'll need to edit the CMake config for this, plus compile the prerequisites (including OpenCV if you plan to use the 2D texture tracker).

**Comment by philip-lamb** [comment]
If you have a working Linux distro, you might just want to edit the compiler flags and see if you can get a local build working. Take a look at the block at https://github.com/artoolkitx/artoolkitx/blob/master/Source/CMakeLists.txt#L203. You'd want to replace `-march=core2` with `-march=armv8-a+crc -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8` and replace `HAVE_INTEL_SIMD` with `HAVE_ARM64_NEON`.

**Comment by philip-lamb** [comment]
Closing as no response from OP.
