### ISSUE TITLE
Add support .glb (glTF 2.0) files

### ISSUE THREAD

**Issue by ViniciusQueiroz-VQ** [artoolkitx/artoolkitx#109]
glTF™ (GL Transmission Format) is a royalty-free specification for the efficient transmission and loading of 3D scenes and models by applications.
It would be interesting if it were implemented in this project. If possible, of course.

**Comment by ThorstenBux** [comment]
@ViniciusQueiroz-VQ artoolkitx is unopinionated about how things are rendered. It merely provides tracking capabilities. You are free to do with the tracking data as you please. For example, in the Web world we pass them on to ThreeJS and as ThreeJS has native support for glTF it is supported. If you are talking native C your best bet would be to find an engine that supports glFT.
Feel free to ping me if you have more questions. 

Going to close this as out of scope.

**Comment by philip-lamb** [comment]
I recently ported the gltf loader from osgEarth into core OpenSceneGraph, and so this would be usable in coordination with the OSG rendering example https://github.com/artoolkitx/artoolkitx/tree/master/Examples/Square%20tracking%20example%20with%20OSG. The gltf plugin port isn't in main OSG yet, but can be found here: https://github.com/MozillaReality/OpenSceneGraph/tree/mozilla-master

**Comment by ViniciusQueiroz-VQ** [comment]
I understand. This is not the responsibility of artookitx.
I am a layman on the subject. 
Could you give me some guidance for this implementation of glTF on android / java? or where can i look?
I’m also going to work with google’s ARCore, and this format would be an attempt to unify things
