### ISSUE TITLE
when build android examples,adb install error.

### ISSUE THREAD

**Issue by tyogit** [artoolkitx/artoolkitx#11]
mlideMacBook-Air:Examples mli$ adb install AR2DTrackingExample-release-unsigned.apk
AR2DTrackingExample-release-unsigned.a...d. 4.2 MB/s (22363223 bytes in 5.099s)
Please select on your phone whether can install the app by The ADB command?
	pkg: /data/local/tmp/AR2DTrackingExample-release-unsigned.apk
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]

if need more infomation,tell me ,when I build it in android studio.it's correct.

**Comment by ThorstenBux** [comment]
What you are describing is no error related to artoolkitX. I guess what happens is that the build apk is unsigned (as the name states) but you are not allowed to install an unsigned apk using adb. When Android Studio is installing the app on your phone it doesn't care whether it is signed or not. But that is just a guess.
