### ISSUE TITLE
Library causes ANR

### ISSUE THREAD

**Issue by artrobert** [artoolkitx/artoolkitx#111]
Hi, I am trying to implement an image recognition-only feature using this library for an Android App but run into a problem, when calling ARController-> stopAndFinal() which calls ARX_jni.arwStopRunning() it seems that it gets blocked and the app is not responding anymore (ANR). 

From my tests it happens randomly in normal use of the app, but if you try to call it right after the screen is opened, it gets to that method and gets blocked. To mention that I could reproduce this also on your example ArSquareTracking (harder than in my app but possible).

Some logs that might help:

 A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
 A/DEBUG: Revision: '26'
 A/DEBUG: ABI: 'arm64'
 A/DEBUG: name: ImageReaderThre 
 A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x52
 A/DEBUG: Cause: null pointer dereference
 A/DEBUG: backtrace:
 A/DEBUG:     /lib/arm64/libARX.so (_ZN11ARTracker2d12loadTwoDDataERNSt6__ndk16vectorIP11ARTrackableNS0_9allocatorIS3_EEEE+116)
 A/DEBUG:     /lib/arm64/libARX.so (_ZN11ARTracker2d6updateEP15AR2VideoBufferTRNSt6__ndk16vectorIP11ARTrackableNS2_9allocatorIS5_EEEE+48)
 A/DEBUG:     /lib/arm64/libARX.so (_ZN12ARController6updateEv+824)
 A/DEBUG:     /lib/arm64/libARX.so (Java_org_artoolkitx_arx_arxj_ARX_1jni_arwUpdateAR+20)
 A/DEBUG:     /oat/arm64/base.odex (offset 0x38000)

 A/libc: failed to wait for crash_dump helper: No child processes
 A/libc: failed to wait for crash_dump helper: No child processes

!UPDATED!

After adding some logs I got to this:
Debug: thread_sub.c:threadWaitQuit
Debug: thread_sub.c: threadWaitQuit: after: pthread_mutex_lock(&(flag->mut))
Debug: thread_sub.c:threadWaitQuit:  after :pthread_cond_signal(&(flag->cond1))
Debug: thread_sub.c:threadWaitQuit: entered while (flag->endF != 2)

The code doesn't get past this method : pthread_cond_wait(&(flag->cond2), &(flag->mut));

**Comment by philip-lamb** [comment]
This is definitely a thread signalling error. As the underlying code has changed a lot, I'm going to close this since I don't think it would be a problem with the new design, but in the event it recurs, we can reopen.
