### ISSUE TITLE
artoolkitx_genMarkerSet can't find image

### ISSUE THREAD

**Issue by moayuisuda** [artoolkitx/artoolkitx#112]
I'm trying to use artoolkit_genMarkerSet on MAC OS, but I keeps getting `image not found` error, I have tried many versions of artoolkit but all get the same result.
However the artoolkit_genTexData can find image with the same image path.
<img width="892" alt="截屏2020-06-08 上午11 09 47" src="https://user-images.githubusercontent.com/37040897/83989381-ce44b380-a978-11ea-92c8-b8bbae203aef.png">

**Comment by philip-lamb** [comment]
😄 The "image not found" error is not coming from artoolkitX, it's coming from macOS, and the "image" it's referring to is the binary of the framework SDL2.

Simple solution: download SDL2.framework from https://www.libsdl.org/release/SDL2-2.0.12.dmg and drop into /Library/Frameworks or ~/Library/Frameworks on your mac.
