### ISSUE TITLE
I have encountered some errors when packaging android on the mac system. It should be necessary to install some dependencies. I tried many methods and it was still unsuccessful. Can you tell me what to do?

### ISSUE THREAD

**Issue by LinearPi** [artoolkitx/artoolkitx#115]
I have encountered some errors when packaging android on the mac system. It should be necessary to install some dependencies. I tried many methods and it was still unsuccessful. Can you tell me what to do?

[error.log](https://github.com/LinearPi/artoolkitxerror/blob/master/%E9%94%99%E8%AF%AF.rtf)
This is the problem I encountered.  Can someone help me？

**Comment by philip-lamb** [comment]
It can't find zlib, or GLES for that matter. 

It looks like it's using some kind of cmake bundled with Unity. You should probably use an official Android SDK release and the cmake toolchain file in that release, rather than using the one from Unity.

**Comment by LinearPi** [comment]
yes. I changed Android  SDk and it succeeded, thanks！
