### ISSUE TITLE
Unable to load jpg image for 2d tracking example

### ISSUE THREAD

**Issue by pranayperiwal** [artoolkitx/artoolkitx#117]
I am running Ubuntu 16.04. 
I managed to build the 2d tracking example. However, the executable in the path ARToolKitX/artoolkitx-master/Examples/2d tracking example/Linux/build does not open.
When I run the executable through the terminal, I get this output:
```
[/Desktop/ARToolKitX/artoolkitx-master/Examples/2d tracking example/Linux/build$ ./artoolkitx_2d_tracking_example
[info] Created OpenGL 3.2+ context.
[info] artoolkitX v1.0.6 initalised.
[info] Loading image data /home/pranay/Desktop/ARToolKitX/artoolkitx-master/Examples/2d tracking example/Linux/build/../share/artoolkitx_2d_tracking_example/pinball.jpg.
[info] Unable to load image '/home/pranay/Desktop/ARToolKitX/artoolkitx-master/Examples/2d tracking example/Linux/build/../share/artoolkitx_2d_tracking_example/pinball.jpg'.
[error] Error: Failed to load trackable.
[error] Error adding marker.
[error] ARVideoView 0 not inited.
[info] artoolkitX finished.
[info] artoolkitX finished.
```
pinball.jpg is actually present in the '2d tracking example' folder. 
Could someone please help me debug this issue? Would really appreciate it.

**Comment by kalwalt** [comment]
Hi @pranayperiwal  can you verify that you have the pinball.jpg image in that path?

**Comment by pranayperiwal** [comment]
Yup, pinball.jpg is present in the mentioned path. Could it be some other problem?

**Comment by pranayperiwal** [comment]
Hi, I managed to get the camera to open. Turns out the folder names were wrong. 
ARToolKitX/artoolkitx-master/Examples/2d tracking example/Linux/build/../share/artoolkitx_2d_tracking_example/
The above path was actually 
ARToolKitX/artoolkitx-master/Examples/2d tracking example/Linux/build/../share/artoolkitx_square_tracking_example/

I guess the people who have created the package need to change that, since this error will arise for everyone then.
But now I am having the problem that the marker is not being detected. Same as https://github.com/artoolkitx/artoolkitx/issues/16

@kalwalt , I noticed that you were trying to help on that issue as well. Do you have any fix for linux? If pinball.jpg wont be detected, can we create our own 2d marker and try?

**Comment by pranayperiwal** [comment]
Just saw the following solution posted 
----------------------------------------------------------------------------
@kalwalt actually i fixed it, first it doesnt work at all with v4l2, you have to use the gstreamer pipe like this (this is for my notebook-webcam)

nftSimple -device=GStreamer "v4l2src device="/dev/video0" ! videoconvert ! video/x-raw,format=RGB,width=640,height=480,framerate=30/1 ! identity name=artoolkit sync=true ! fakesink"

but there is also another issue with cli-args (precisely the gstreamer arg) not parsed correctly, the beginning of main in nftSimple has to look like this (it is exactly how simpleTest is parsing the args):

'
...
int main(int argc, char** argv)
{
char glutGamemode[32];
char *cparam_name = NULL;
char vconf[512];
const char markerConfigDataFilename[] = "Data2/markers.dat";
int i;

if( argc == 1 ) vconf[0] = '\0';
else {
    strcpy( vconf, argv[1] );
    for( i = 2; i < argc; i++ ) {strcat(vconf, " "); strcat(vconf,argv[i]);}
}

#ifdef DEBUG
arLogLevel = AR_LOG_LEVEL_DEBUG;
#endif

//
// Library inits.
//

glutInit(&argc, argv);

...
'

after that the pinball image works showing a small cube

---------------------------------
Could you help me understand how to implement the above steps?
1. Where should I put this: 
`nftSimple -device=GStreamer "v4l2src device="/dev/video0" ! videoconvert ! video/x-raw,format=RGB,width=640,height=480,framerate=30/1 ! identity name=artoolkit sync=true ! fakesink"`

2. Where is nftSimple? I cannot find such a file. Could dumb this down and help me locate the file I need to put the remaining code in? Would really appreciate the help. I'm new to the ARToolKit world.

**Comment by philip-lamb** [comment]
Closing as jpeg loading has been recently addressed.
