### ISSUE TITLE
About the algorithm used in making the NFT mark

### ISSUE THREAD

**Issue by badwoman0919** [artoolkitx/artoolkitx#125]
Hello, may I ask the part about making NFT mark？When I use the genTexData tool to obtain the data set, what kind of algorithm is used to obtain the result? Is it SURF algorithm or ORB algorithm? Or is it an algorithm developed by you yourself?

**Comment by philip-lamb** [comment]
For the older-style genTexData tracking, two different tracking types are used. FREAK features are used for image matching and initial pose extraction. This is provided by libKPM and you can look at the source for how that is done. Once an initial pose is found, template matching is used, and this is in libAR2.

I've added a link to a document on the wiki page https://github.com/artoolkitx/artoolkitx/wiki/Creating-and-using-NFT-markers https://github.com/artoolkitx/artoolkitx/wiki/docs/Natural%20Point%20Feature%20Tracking%20of%20a%20textured%20plane%20-%20A%20Real%20Time%20Augmented%20Reality%20Application%20-%20Florent%20Vial%20-%202003.pdf
