### ISSUE TITLE
Automatic build system

### ISSUE THREAD

**Issue by ThorstenBux** [artoolkitx/artoolkitx#134]
Hi @philip-lamb ,

How are you? Your latest commit broke all the automatic builds. Is it worth fixing or are there more changes coming?
Cheers

**Comment by ThorstenBux** [comment]
Copy that, let me know if you need anything.

**Comment by kalwalt** [comment]
@philip-lamb @ThorstenBux based on your recent commit/changes i think the code could be compiled with C++17 compiler, `throw's` was an obstacle for doing this. Have you tried to compile it with the C++17 compiler?

**Comment by philip-lamb** [comment]
There aren't any C++17-specific language features used in the project, but I am working to resolve any forward-compatibility issues.

**Comment by philip-lamb** [comment]
Working as of 1.0.7.
