### ISSUE TITLE
Ubuntu - Thresholding not updating

### ISSUE THREAD

**Issue by robertinonicolazzi** [artoolkitx/artoolkitx#14]
Well like the title says, im running square tracking example but the thresholding is not updating

if i focus the camera to marker on first frame. The cube appears but never go away, its like the thresholding never update

**Comment by robertinonicolazzi** [comment]
please someone can help me :(

**Comment by ThorstenBux** [comment]
@robertinonicolazzi Can you please elaborate a bit more what example you are running and how you try to update the threshold. Or what you understand as threshold update for that matter.

**Comment by robertinonicolazzi** [comment]
Hello @ThorstenBux, im using Square Tracking Example. When i change to debug mode to see black/white image this image never updated, its "stack" in the first frame that my camera see

**Comment by ThorstenBux** [comment]
@robertinonicolazzi thanks, will have a look

**Comment by robertinonicolazzi** [comment]
any news about this?

**Comment by ThorstenBux** [comment]
I should dive into that but unfortunately totally occupied by other things.

**Comment by ThorstenBux** [comment]
@robertinonicolazzi I've downloaded the latest release and build the example and ran it. I'm getting a video stream and can see a color video. When hitting the `d` button to enable debug mode I still see a color video but the output on the terminal changes to show more information. Meaning I don't see any black/white image and the video isn't stuck. Could you please detail how you actually get to a black/white image in the first place?

**Comment by robertinonicolazzi** [comment]
@ThorstenBux hello friend, i've allready download the lastest code and build from source and everything work great now. I dont know what happen before, because i installed in the same way.
Otherwise thanks a lot for your time.! i use artoolitx for my final project in computer science so thanks a lot again!
