### ISSUE TITLE
Bugged camera in android 12

### ISSUE THREAD

**Issue by Serpent03** [artoolkitx/artoolkitx#149]
![image](https://user-images.githubusercontent.com/66001658/231711841-ff7d3fd3-00a6-414f-a09e-6f226374598b.png)

When the application starts, it displays this glitched out camera. Using default settings, 2D Simple scene.

**Comment by GuilhermeBrisida** [comment]
I tried opening the sample app "2d tracking example" on Android 13, same problem.
