### ISSUE TITLE
Build script fails under Ubuntu 22.04

### ISSUE THREAD

**Issue by kalwalt** [artoolkitx/artoolkitx#150]
I was trying to build the source code latest from master `1.1.5` version, i used these steps:

```
// installed all dependencies with sudo apt install 
cd Source
./build linux examples
```

The script exit at line https://github.com/artoolkitx/artoolkitx/blob/9d5ec0ed3b93cff61298fc1cc263f6d255f3b822/Source/build.sh#L379 with message
`No current prebuilt OpenCV available`
note that i opencv dependencies installed with `sudo apt install libopencv-dev`
How to solve: comment out the `exit -1` line and run again the script, the build process will be successfull.

Note as written in the title i tested under Ubuntu 22.04.

**Comment by philip-lamb** [comment]
It should be finding any manually-installed package. Can you post the output of `apt-cache --quiet=1 policy libopencv-dev` on your system?

**Comment by kalwalt** [comment]
This is the output:
```
apt-cache --quiet=1 policy libopencv-dev
libopencv-dev:
  Installato: 4.5.4+dfsg-9ubuntu4
  Candidato:  4.5.4+dfsg-9ubuntu4
  Tabella versione:
 *** 4.5.4+dfsg-9ubuntu4 500
        500 http://it.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
        100 /var/lib/dpkg/status

```
That is correct, but the build script expect an older Linux/Ubuntu version nad so the libopencv-dev should be 3.4.*: now i realized that the script is "correct" because is expecting that version.

And making this changes:
```
if (type dpkg-query >/dev/null 2>&1) ; then
        if (apt-cache --quiet=1 policy libopencv-dev | grep -E 'Installato: (4|5)\.') ; then
            echo "Using installed OpenCV"
        else
            if (apt-cache --quiet=1 policy libopencv-dev | grep -E 'Candidato: (4|5)\.') ; then
                echo "Installing OpenCV"
                sudo apt-get install libopencv-dev
            else
                echo "No current prebuilt OpenCV available"
                exit -1
```
The script will works as expected for me. Note the changes in version and `Installed -> Installato` `Candidate -> Candidato` to adapt to my default language.

**Comment by philip-lamb** [comment]
Agreed, it's a bug based on having to manually parse localised text to get the version. I'll see if I can find a more reliable method that is locale-independent.

**Comment by philip-lamb** [comment]
@kalwalt Could you see if this temporarily overrides your local settings? `LC_ALL=”C” apt-cache --quiet=1 policy libopencv-dev`?

**Comment by kalwalt** [comment]
yes it overrides my local settings:
```
LC_ALL=”C” apt-cache --quiet=1 policy libopencv-dev
libopencv-dev:
  Installed: 4.5.4+dfsg-9ubuntu4
  Candidate: 4.5.4+dfsg-9ubuntu4
  Version table:
 *** 4.5.4+dfsg-9ubuntu4 500
        500 http://it.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
        100 /var/lib/dpkg/status
```
I think this will fix that issue.
Do you plan also to restore 
https://github.com/artoolkitx/artoolkitx/blob/9d5ec0ed3b93cff61298fc1cc263f6d255f3b822/Source/build.sh#L380-L385
with a newer opencv version 4.5 or 4.6?

**Comment by philip-lamb** [comment]
OK, good to know. I'll push a fix for this soon. And no, since OpenCV is now available as a package in the distro, it saves a lot of work to not have a separate precompiled version.

**Comment by kalwalt** [comment]
Thank you i will test the script again with your latest commit https://github.com/artoolkitx/artoolkitx/pull/151/commits/f057b45df8c3924d145590badd27ac1ecb2b3f48
