### ISSUE TITLE
How to make artoolkit not use camera, but realize nft detection through external incoming frame data

### ISSUE THREAD

**Issue by FatPaper** [artoolkitx/artoolkitx#152]
On the Android platform, I want to use camerax for preview, and artoolkitx only does detection and tracking, but I found that artoolkitx has opened and accessed the camera inside. In this case, when I use camerax to preview and then arwStartRunning, artoolkit will exit the program because the camera connection is closed. I have tried -nonative these configurations, but I don't know the specific role, and I can't find relevant documents, what should I do? I'm not proficient in the c++ code inside, and I don't know where to modify it

**Comment by FatPaper** [comment]
@smarter @philip-lamb

**Comment by philip-lamb** [comment]
You can (in theory) do this at the moment using the legacy arwVideoPush* functions, but this is not really a supported path. I'm in the process of adding support for external video sources cross-platform, so this will become a lot easier. This support will be complete soon (within approx 2 weeks).
