### ISSUE TITLE
I tried opening the sample app "2d tracking example" on Android 13, same problem.

### ISSUE THREAD

**Issue by Serpent03** [artoolkitx/artoolkitx#153]
I tried opening the sample app "2d tracking example" on Android 13, same problem.

_Originally posted by @GuilhermeBrisida in https://github.com/artoolkitx/artoolkitx/issues/149#issuecomment-1533744357_
           
Hi, I solved this issue by changing the resolution of the camera. Apparently it does not automatically fit in the camera resolution accordingly, so you have to select the correct ratio yourself.

For me it was 1920x864. You can try changing the resolution from the gear setting in the app.

**Comment by philip-lamb** [comment]
@Serpent03 Which release was this with? The sample should only be using one of the available resolutions as reported by the camera framework, so if it's not, I need to trace the bug.

**Comment by Serpent03** [comment]
@philip-lamb 1.1.5, in Unity Android and cmake -> Android Studio both
