### ISSUE TITLE
Question: what is configuration? 

### ISSUE THREAD

**Issue by MrApple100** [artoolkitx/artoolkitx#157]
I had tried build example 2d tracking, and i get something error with version of cmake, ndk, visual studio, msvsbuildtools, android sdk? May you tell me what version correctly you use? 
Should i use Linux, or there is instruction for Windows 10 x64?
Thanks in advance

**Comment by philip-lamb** [comment]
If you want to use Windows 10 x64 and just build and run the examples, you should be able to do this by downloading a release SDK and loading the Visual Studio project file for the example, and then building and running within Visual Studio. If this doesn't work, then please file additional bugs.

If you want to build the SDK yourself, you'll need some additional tooling, depending on which platform you want to support, but at minimum on Windows you'll need git-bash or WSL installed. git-bash comes with the official git release, or WSL is installable from the Windows Store. Then follow the instructions https://github.com/artoolkitx/artoolkitx/wiki/The-artoolkitX-build-system
