### ISSUE TITLE
Different input size，like set Android resolution 480*360, but got cvMat 640*480

### ISSUE THREAD

**Issue by Gotta-C** [artoolkitx/artoolkitx#167]

**Comment by philip-lamb** [comment]
Can you provide more information about what you did, what you observed, and what the expected results were?

**Comment by Gotta-C** [comment]
non-rigid object as marker,  or the print A4 paper, the distort  or extreme perspective will causes a instability pose, how to get a stable pose, is there any strategy？ I tried to select tracking points by filter some serious distort pts but not improved.
