### ISSUE TITLE
building for Unity

### ISSUE THREAD

**Issue by slowizzm** [artoolkitx/artoolkitx#17]
I see the .zip's for Unity in the artoolkitx 1.0.1  release. I know arunityx is supposed to release in the near future, until then is there some documentation on how to get artkx working in Unity 2017.4 LTS?

**Comment by ThorstenBux** [comment]
That's a bit tricky. You could use these artefacts and use it together with the arunity5 plugin. However, artoolkitX breaks the interface. Which means you need to have a look at ARController.h https://github.com/artoolkitx/artoolkitx/blob/master/Source/ARX/include/ARX/ARController.h and match them to the external API calls from the unity plugin eg. https://github.com/artoolkitx/arunity5/blob/master/src/Unity/Assets/ARToolKit5-Unity/Scripts/ARNativePluginStatic.cs That would most likely work for all platforms except Android. 

Also, keep in mind that arunityX will contain changes to the actual scripts that are part of the Unity3D plugin itself.
