### ISSUE TITLE
Feeding in custom frames

### ISSUE THREAD

**Issue by XrizZ** [artoolkitx/artoolkitx#18]
Hi there,
I'd like to use the ARController to detect markers from a RAW RGB\RGBA BYTE buffer and not use the libARVideo class for connecting to the camera. Instead, I already have all my frames decoded and ready to be computed. Is this possible with the current version of artoolkitx? Or would I have to change the library myself?
Thanks!

**Comment by philip-lamb** [comment]
It's a capability that would be useful to have, but not currently supported. One option for a quick workaround would be to modify the dummy video source and have it call your code back from ar2VideoGetImageDummy function.

I'll keep this open as a feature request.

**Comment by XrizZ** [comment]
I've modified the source by adding a video class for "Buffer" and adapted the ARController::update() function to: bool update(AR2VideoBufferT* leftBuffer = NULL, AR2VideoBufferT* rightBuffer = NULL);

If video type is buffer and at least one buffer is non zero, then the function will update the controller and perform the tracking directly from that buffer. It works well in my tests. If you are interested, I can commit the code if you give me permission.

**Comment by ThorstenBux** [comment]
@XrizZ please commit your changes to your fork of artoolkitX and open a PullRequest. Then we can review your changes and merge. If you need support with that please let me know.

**Comment by ThorstenBux** [comment]
@XrizZ let me know if you need support to push your code. I'd like to review it.

**Comment by XrizZ** [comment]
@ThorstenBux sorry about the delay, I'll share the code with you this week!

**Comment by philip-lamb** [comment]
This functionality has been added in https://github.com/artoolkitx/artoolkitx/pull/160
