### ISSUE TITLE
JavaScript version of ARToolKitX

### ISSUE THREAD

**Issue by vitorpmoreira** [artoolkitx/artoolkitx#2]
Cheers,

By any chance, are you considering maintaining/providing a JavaScript version, using emscripten to compile c/c++ to asm.js or even Wasm.js?

**Comment by ThorstenBux** [comment]
It is on the list but can't say a specific date for it at the moment. We would highly appreciate community contributions to speed-up the process.

**Comment by SystemDiagnosticss** [comment]
Any progress in this field?

**Comment by ThorstenBux** [comment]
https://github.com/augmentmy-world/artoolkitX.js

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
