### ISSUE TITLE
Module Dependencie

### ISSUE THREAD

**Issue by itk0492** [artoolkitx/artoolkitx#20]
Hi, 

I cannot add the .aar as a module dependencie, it simply doesn't show as a module when I add it.
Does anyone knows a solution to this?

I'm using AS 3.1.2

Thank you

**Comment by ThorstenBux** [comment]
Did you follow these steps?
https://github.com/artoolkitx/artoolkitx/wiki/Setting-up-for-developing-an-artoolkitX-for-Android-app

**Comment by itk0492** [comment]
Yes, I managed to make it function with those steps, is running well, thank you.
