### ISSUE TITLE
Displaying the video

### ISSUE THREAD

**Issue by Relo4ded** [artoolkitx/artoolkitx#22]
Hello,
im currently trying out the toolkit on MacOs. I created a Cocoa Application and am able to import the toolkit and load the camera. But I can't get the Video image to display in my Sceneview. The drawVideo function says that it displays to the current OpenGl context, I tried to set the scenes context using the CGLSetCurrentContext but nothing is displayed.Is there any Documentation for the drawVideo functions , I can't find any. There is a warning which says "[warning] ARG: Request for to render multi-planar pixel format in colour not supported. Will render in mono." but I don't really get whats going on there. The example project works on this Mac, can you help me out with my problem?

**Comment by philip-lamb** [comment]
@Relo4ded Do other OpenGL rendering commands work in the context you've created. E.g. can you draw a simple triangle or something?
