### ISSUE TITLE
Markerless tracking

### ISSUE THREAD

**Issue by XrizZ** [artoolkitx/artoolkitx#23]
Have you thought about implementing a markerless tracking yet? In apples ARkit, it is possible to track planes/surfaces instead, which makes for a great AR experience not having to worry about custom markers. How far away are we from an implementation into artoolkitx? Has anyone attempted at implementing this themselves?

**Comment by ThorstenBux** [comment]
Hi, yes we have concrete thoughts on implementing markerless tracking and capabilities like ARKit. Can't give you a timeline yet, though.
