### ISSUE TITLE
unresolved external symbol

### ISSUE THREAD

**Issue by snowymo** [artoolkitx/artoolkitx#24]
I am using windows and vs2017.

I ran `build.sh` in source folder and build the solution.

Some linking problems happened. Actually the lib is in the correct place. I don't know why.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol __imp_arVideoSaveImageJPEG	artoolkitx_check_id	
Error	LNK1120	1 unresolved externals	artoolkitx_check_id	
Error	LNK2001	unresolved external symbol __imp_arPattSave	artoolkitx_genMarkerSet	
Error	LNK1120	1 unresolved externals	artoolkitx_genMarkerSet		
Error	LNK2019	unresolved external symbol __imp_ar2GenFeatureMap referenced in function main	artoolkitx_genTexData	
Error	LNK2019	unresolved external symbol __imp_ar2FreeFeatureMap referenced in function main	artoolkitx_genTexData	
Error	LNK2019	unresolved external symbol __imp_ar2SelectFeature2 referenced in function main	artoolkitx_genTexData	
Error	LNK1120	3 unresolved externals	artoolkitx_genTexData	
Error	LNK2001	unresolved external symbol __imp_arPattSave	artoolkitx_mk_patt	
Error	LNK1120	1 unresolved externals	artoolkitx_mk_patt	
```

**Comment by ThorstenBux** [comment]
Hi @snowymo ,

can you please detail the `build.sh` command you called to build it and where this linking issues happened? Inside Visual Studio or on the Terminal?

**Comment by snowymo** [comment]
This is the [build.sh](https://github.com/artoolkitx/artoolkitx/blob/master/Source/build.sh) I used and I ran it in terminal.

**Comment by ThorstenBux** [comment]
Thanks, and the exact command how you called it?

**Comment by snowymo** [comment]
I called it with `./build.sh windows `to generate the solution.

By the way, does ARToolkitX support feed static image as input for marker detection?

**Comment by ThorstenBux** [comment]
For me it looks like you have trouble building the Utilities but the library builds alright.

Yes artoolkitX supports static images as input: https://github.com/artoolkitx/artoolkitx/wiki/artoolkitX-video-module-configuration-reference#ar_video_module_image

**Comment by snowymo** [comment]
Yes and i manually move the implementation of the unresolved methods to other ***.c file that in the same project. I can get the solution built. I just don't know why it does not work at the beginning.

By the way, the camera I am using is OV580 and I wanna run check_id. But kind of it does not capture the frame. I remember I ran check_id in ARUnity5 with the same hardware. Although the pixel format looks wrong, but I still get image and some detection results.

**Comment by ThorstenBux** [comment]
Actually, you are calling ```build.sh windows``` from a GitBash shell right?

**Comment by snowymo** [comment]
I use git bash actually so that I can see the log. I don't knowthe version but it shows MINGW64.
VS 2017 15.4.5
Win 10 too.

**Comment by ThorstenBux** [comment]
Could you maybe update VS? I've seen some issue with previous versions.

**Comment by snowymo** [comment]
Since this could be fixed manually, I think the priority is not that high. Just some small changes we need to do for cmake. I already did that in my fork repo. 

I hope you can help me with the [static image issue](https://github.com/artoolkitx/artoolkitx/issues/27).

And also any idea about generate customized camera parameter file as input?

Thanks

**Comment by ThorstenBux** [comment]
@snowymo could you please open a PullRequest for your cmake script changes. I'll close the issue as it builds fine on the CI machine but would like to review your changes.
