### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by huyaohua-love** [artoolkitx/artoolkitx#25]
Who succeeded in running? None of these APK can run.

run android Examples:

E/libAR: [error] ARController::androidVideoPush2: ARVideoSource is not running.
E/libAR: [error] ARController::androidVideoPush2: ARVideoSource is not running.

**Comment by ThorstenBux** [comment]
Hi @huyaohua-love I'm sorry to hear that. 

Can you please describe what steps you took to try to run the apps?
I'm guessing you are talking about Android, right?

**Comment by ThorstenBux** [comment]
Closing as no response
