### ISSUE TITLE
How to use a static image as input to detect the pattern

### ISSUE THREAD

**Issue by snowymo** [artoolkitx/artoolkitx#27]
I was provided this page [AR_VIDEO_MODULE_IMAGE](https://github.com/artoolkitx/artoolkitx/wiki/artoolkitX-video-module-configuration-reference#ar_video_module_image).

I hope there are more detail tutorial for me to set up.

Thanks

**Comment by snowymo** [comment]
I tried to specify the parameter as
`"--module=Image -width=" + std::to_string(width) + " -height=" + std::to_string(height) + " -format=MONO -image=" + jpgName)`
and it failed to read the image in this function `jpeg_read_header`

The image I get is generated by stbi_image APIs because the original image is pgm file. I wonder is there any example image file for me to try?

**Comment by snowymo** [comment]
Ignore the last one. I was using write_to_png to write a jpg file.

New problem is the reading jpg part. The view shows different resolution comparing to the original image file.

Here is the screenshot of the window.
![artoolkit-loadimage](https://user-images.githubusercontent.com/10137769/41749458-715a14a0-7584-11e8-9bcb-071d7bc3d52f.PNG)

Here is the original image.
![hiro](https://user-images.githubusercontent.com/10137769/41749463-778920f0-7584-11e8-8ee6-526f992660c4.jpg)

**Comment by ThorstenBux** [comment]
@snowymo have your found a solution yet? Would be good to know as I haven't done much with static images so far.

**Comment by philip-lamb** [comment]
This bug doesn't reference the platform used, but if it was macOS or iOS, there was a bug in libjpeg linkage which resulted in failed jpeg reading. This was addressed in https://github.com/artoolkitx/artoolkitx/commit/a1f54fe5bfa4ed041ffff10f3cb8bb0643bdf938
