### ISSUE TITLE
artoolkitx in Odroid UX4 with mali

### ISSUE THREAD

**Issue by jage92** [artoolkitx/artoolkitx#28]
I'm trying to run the Square Tracking example on an Odroid UX4 with Ubuntu Armbian image. I have managed to compile the linux version on this board by changing the CMake configuration files and I can run the example with the OpenGL Mesa libraries, but it runs very slowly. Due to this fact, I am trying to use libmali libraries that I think will be faster than the mesa libraries, but I have this error "Error creating window: Could not initialize EGL". 

Has anyone tried to do anything similar? 

Thank you for your time

**Comment by philip-lamb** [comment]
The hardware is more than capable of running artoolkitX nice and fast, so its just a matter of figuring out the config. I would start with making sure you get Video4Linux delivering frames in one of the YUV video formats. That will avoid the costly YUV-RGBA conversion in the driver and save time in artoolkitX processing too.

In the square tracking example, set vconf = "-format=0 -palette=NV21" and see how you get on.
