### ISSUE TITLE
How to detect multimarker in ARToolkitX

### ISSUE THREAD

**Issue by snowymo** [artoolkitx/artoolkitx#29]
I found an example called square tracking example which can detect single marker like Hiro and Kanji. I wanna try multimarkers, like the multi-barcode-4x3.

I ran corresponding example scene in arunity5 and it works. So I copy the config string, which is "multi; multi-barcode-4x3.dat". The height parameter does not work here, I cannot change default height 40 to my height by the way. I can confirm that the marker is being loaded successfully, the UID is 0 all the time not like unity, which will be increased after every play.

Then I ran the square tracking example and it failed to find the markers. However, arunity5 can find them.

So any sample for multimarker c++ project or how do I set the parameter?

Thanks

**Comment by ThorstenBux** [comment]
@snowymo could you maybe share the example that you modified?

Additionally, I need the platform you are running and compiling on to reproduce what you are trying todo?

**Comment by philip-lamb** [comment]
The most likely issue is that you need a more complete path to the file multi-barcode-4x3.dat. In the square tracking example, the marker name is appended to the resources directory path. The form of the resources directory path is platform-specific, so which platform are you on? On Linux and Windows, it takes the form of executable_name.exe/../share/executable_name/

As regards the size parameter; in multi-marker sets, the size is defined for each marker in the set in the dat file.
