### ISSUE TITLE
How to run square-tracking-example with vconf parameters

### ISSUE THREAD

**Issue by vgenten** [artoolkitx/artoolkitx#31]
Hello,
I'm trying to run the artoolkitx square_tracking_example with a Intel RealSense D435 Camera.
I like to use the --vconf option since the default input device is the depth stream (pixel format Z16).
Therefore the vconf string i like to use is :
"-module=V4L2  -dev=/dev/video2 -width=1920 -height=1080 -framerate=30"
All parameters should work but executing this gives me the error 
"[error] No video source or video source is closed."
Running it without the "-framerate" option gives me a green screen.

How can I run the example with the parameters from above?
Thank you for your support.

**Comment by philip-lamb** [comment]
I don't have this camera, so all I can suggest is that you try to verify settings that work in another Video4Linux2 application, and see if you can then adapt them to artoolkitX. The options are listed at https://github.com/artoolkitx/artoolkitx/wiki/artoolkitX-video-module-configuration-reference#ar_video_module_v4l2

In particular, if dealing with a multi-channel device, you might need option -channel=, and for devices putting out anything other than RGBA, you'll usually need to specify a -palette= option. Also pass -format=0 if you don't want it converted back to RGBA.

**Comment by philip-lamb** [comment]
Full vconf options are here: https://github.com/artoolkitx/artoolkitx/wiki/artoolkitX-video-module-configuration-reference
