### ISSUE TITLE
ArToolKitX with eclipse, error on run

### ISSUE THREAD

**Issue by robertinonicolazzi** [artoolkitx/artoolkitx#38]
Hello friend, i want to know if someone has been working with artoolkitx and eclipse and can help me

All the project compile perfect (based on square tracking example ITS THE SAME CODE), but when the app runs
the windows just close after glClearColor()

this happen after the first frame is captured, but appareantly everything just break when i do glClearColor

EDIT: My dev platform is linux and my targeting is linux

**Comment by philip-lamb** [comment]
What platform are you developing on and what platform are you targeting?

**Comment by robertinonicolazzi** [comment]
@philip-lamb linux and linux philip.

**Comment by robertinonicolazzi** [comment]
If someone is interested with this simple makefile, everything works okey. im continue trying to make it run with eclipse building system

``
CXXFLAGS =	-std=c++11 -O2 -g -Wall -fmessage-length=0 

OBJS =		include/draw.o Prueba1.o

LIBS = -lSDL2 -lGL -lGLU -lglut -lARX -lGLEW -Iinclude 

TARGET =	Prueba1

$(TARGET):	$(OBJS)
	$(CXX) -o $(TARGET) $(OBJS) $(LIBS)

all:	$(TARGET)

clean:
	rm -f $(OBJS) $(TARGET)

**Comment by philip-lamb** [comment]
You’re going to need to define the preprocessed symbol ARX_TARGET_PLATFORM_LINUX=1 either in Eclipse or by adding it to your source before any artoolkitX includes.
