### ISSUE TITLE
mk_patt.exe error IMFSourceReader::ReadSample

### ISSUE THREAD

**Issue by FREEZX** [artoolkitx/artoolkitx#39]
Hi,
I'm trying to use the mk_patt util from the latest release.
I'm repeatedly getting this error:
```
Error: IMFSourceReader::ReadSample
```
and i get a white window displayed.

I'm running on Windows 10

**Comment by FREEZX** [comment]
Related issue:
https://github.com/jeromeetienne/AR.js/issues/296

**Comment by ThorstenBux** [comment]
@FREEZX works like a charm for me. Can you run it from Command and past the log here, please

**Comment by FREEZX** [comment]
Huh, that's odd. It's working now, after a reboot. Closing :/

**Comment by ThorstenBux** [comment]
Might be your camera was blocked by another process
