### ISSUE TITLE
Cannot do CMake using latest master branch

### ISSUE THREAD

**Issue by XrizZ** [artoolkitx/artoolkitx#4]
When trying to cmake the examples, the following error occurs:
`<FindSDL2.cmake>
</FindSDL2.cmake>
-- Could NOT find OpenGLES2 (missing:  OPENGLES2_LIBRARIES OPENGLES2_INCLUDE_DIR)
/usr/usr/local/opt/localC:/Users/Chris/Desktop/artoolkitx-master/artoolkitx-master/Examples/Square tracking example/Windows/../../../Source/depends/windows/include
CMake Error at CMakeLists.txt:68 (include):
  include could not find load file:
C:/Users/Chris/Desktop/artoolkitx-master/artoolkitx-master/Examples/Square tracking example/Windows/../../../SDK/lib/ARX/ARX.cmake
Configuring incomplete, errors occurred!`

Are there files missing in the repository?

**Comment by ThorstenBux** [comment]
No, the files are definitely not missing in the repository. You need to run ```./build.sh <<platform>>``` in order to build

**Comment by ThorstenBux** [comment]
From a git-bash shell

**Comment by XrizZ** [comment]
Thank you Thorsten, calling build.sh from git-bash solves the problem I had in CMake GUI.
