### ISSUE TITLE
IMPORTANT: camera calibration server down

### ISSUE THREAD

**Issue by ThorstenBux** [artoolkitx/artoolkitx#40]
Dear community,

the camera calibration server is down. That might affect the behavior of your apps. I'm sorry for the inconvenience.

Kind regards
Thorsten Bux

**Comment by philip-lamb** [comment]
Up now.

**Comment by DrewDahlman** [comment]
What is the URL for this?

**Comment by philip-lamb** [comment]
https://github.com/artoolkitx/artoolkitx/blob/master/Source/ARX/ARVideo/cparamSearch.c#L101

**Comment by DrewDahlman** [comment]
Sweet! Is there a way to get the dat files for newer devices? I see the old utils for up to iPhone6s but cannot find anything for iPhone 7+ I am using jsartoolkit btw and needing the camera_para.dat file for multiple devices...
