### ISSUE TITLE
2d Barcode support

### ISSUE THREAD

**Issue by jeunetoujour** [artoolkitx/artoolkitx#44]
There is some documentation on doing 2d Barcodes such as 3x3 to 5x5 with hamming codes ect. The interface is no exposed in Artoolkitx for at least the Android built library. 

These are missing:

arSetPatternDetectionMode(arHandle, AR_MATRIX_CODE_DETECTION);
arSetMatrixCodeType(arHandle, AR_MATRIX_CODE_3x3_HAMMING63);

It could use an example as well.

**Comment by ThorstenBux** [comment]
Hi there,

the function you are searching for is exposed just a bit different then expected: https://github.com/artoolkitx/artoolkitx/blob/master/Source/ARX/ARX_c.cpp#L333

There you can set what you are looking for. 

Code doc (but I admit that could do with improvement) http://www.artoolkitx.org/artoolkitx/Documentation/APIReference/ARX/html/class_a_r_tracker_square.html#ab2bc924411b08fec5f392280351fe3d8

**Comment by jeunetoujour** [comment]
I'm sorry, but I'm not following. I dont see most things in the Android build. I was needing this for Android/Java.

**Comment by ThorstenBux** [comment]
that is the JNI mapping: https://github.com/artoolkitx/artoolkitx/blob/master/Source/ARXJ/ARXJProj/arxj/src/main/java/org/artoolkitx/arx/arxj/ARX_jni.java#L493

**Comment by philip-lamb** [comment]
Once you have a native instance, you can just call the static methods:

```
ARX_jni.arwSetTrackerOptionInt(ARW_TRACKER_OPTION_SQUARE_PATTERN_DETECTION_MODE, AR_MATRIX_CODE_DETECTION);
ARX_jni.arwSetTrackerOptionInt(ARW_TRACKER_OPTION_SQUARE_MATRIX_CODE_TYPE, AR_MATRIX_CODE_3x3_HAMMING63);
```
