### ISSUE TITLE
android crashed with parameter -format=RGBA

### ISSUE THREAD

**Issue by rainfallljs** [artoolkitx/artoolkitx#49]
can android device run with format of "RGBA"?
how can I get image data with the format of "RGBA"?
thank you

**Comment by philip-lamb** [comment]
You have two choices here. Either you can request from Android.Camera2 RGBA frames, or you can have ARX convert the YUV frames to RGBA on the native side.

If you want to get RGBA frames from Android, you need to make two changes in artoolkitx/Source/ARXJ/ARXJProj/arxj/src/main/java/org/artoolkitx/arx/arxj/camera/CameraSurfaceImpl.java, changing YUV_420_888 to RGBA in two places.
