### ISSUE TITLE
Can't build artoolkitx on linux platform

### ISSUE THREAD

**Issue by Learningm** [artoolkitx/artoolkitx#54]
Hi.
I have installed all required library in the System-requirements page on Ubuntu14.04, some libraries are updated to a new version, such as libavcodec58 and libavformat58 and libpng16-35, but I think it should't cause the failure. When I build from source code, I got something error like the following:

/data/project/artoolkitx/artoolkitx-master/Source/ARX/ARVideo/Video4Linux2/videoV4L2.c: In function ‘printPalette’:
/data/project/artoolkitx/artoolkitx-master/Source/ARX/ARVideo/Video4Linux2/videoV4L2.c:158:15: error: ‘V4L2_PIX_FMT_ARGB444’ undeclared (first use in this function)
         case (V4L2_PIX_FMT_ARGB444): s = "ARGB444"; break;
               ^
/data/project/artoolkitx/artoolkitx-master/Source/ARX/ARVideo/Video4Linux2/videoV4L2.c:158:15: note: each undeclared identifier is reported only once for each function it appears in
/data/project/artoolkitx/artoolkitx-master/Source/ARX/ARVideo/Video4Linux2/videoV4L2.c:159:15: error: ‘V4L2_PIX_FMT_XRGB444’ undeclared (first use in this function)
         case (V4L2_PIX_FMT_XRGB444): s = "XRGB444"; break;
               ^
/data/project/artoolkitx/artoolkitx-master/Source/ARX/ARVideo/Video4Linux2/videoV4L2.c:160:15: error: ‘V4L2_PIX_FMT_ARGB555’ undeclared (first use in this function)
         case (V4L2_PIX_FMT_ARGB555): s = "ARGB555"; break;
               ^
/data/project/artoolkitx/artoolkitx-master/Source/ARX/ARVideo/Video4Linux2/videoV4L2.c:161:15: error: ‘V4L2_PIX_FMT_XRGB555’ undeclared (first use in this function)
         case (V4L2_PIX_FMT_XRGB555): s = "XRGB555"; break;
               ^
/data/project/artoolkitx/artoolkitx-master/Source/ARX/ARVideo/Video4Linux2/videoV4L2.c:163:15: error: ‘V4L2_PIX_FMT_ARGB555X’ undeclared (first use in this function)
         case (V4L2_PIX_FMT_ARGB555X): s = "ARGB555X"; break;
               ^
/data/project/artoolkitx/artoolkitx-master/Source/ARX/ARVideo/Video4Linux2/videoV4L2.c:164:15: error: ‘V4L2_PIX_FMT_XRGB555X’ undeclared (first use in this function)
         case (V4L2_PIX_FMT_XRGB555X): s = "XRGB555X"; break;
               ^
/data/project/artoolkitx/artoolkitx-master/Source/ARX/ARVideo/Video4Linux2/videoV4L2.c:169:15: error: ‘V4L2_PIX_FMT_ABGR32’ undeclared (first use in this function)
         case (V4L2_PIX_FMT_ABGR32): s = "ABGR32"; break;
               ^
/data/project/artoolkitx/artoolkitx-master/Source/ARX/ARVideo/Video4Linux2/videoV4L2.c:170:15: error: ‘V4L2_PIX_FMT_XBGR32’ undeclared (first use in this function)
         case (V4L2_PIX_FMT_XBGR32): s = "XBGR32"; break;
               ^
/data/project/artoolkitx/artoolkitx-master/Source/ARX/ARVideo/Video4Linux2/videoV4L2.c:171:15: error: ‘V4L2_PIX_FMT_ARGB32’ undeclared (first use in this function)
         case (V4L2_PIX_FMT_ARGB32): s = "ARGB32"; break;
               ^
/data/project/artoolkitx/artoolkitx-master/Source/ARX/ARVideo/Video4Linux2/videoV4L2.c:172:15: error: ‘V4L2_PIX_FMT_XRGB32’ undeclared (first use in this function)
         case (V4L2_PIX_FMT_XRGB32): s = "XRGB32"; break;
               ^
/data/project/artoolkitx/artoolkitx-master/Source/ARX/ARVideo/Video4Linux2/videoV4L2.c: In function ‘ar2VideoOpenV4L2’:
/data/project/artoolkitx/artoolkitx-master/Source/ARX/ARVideo/Video4Linux2/videoV4L2.c:449:36: error: ‘V4L2_PIX_FMT_ABGR32’ undeclared (first use in this function)
                     vid->palette = V4L2_PIX_FMT_ABGR32;
                                    ^
/data/project/artoolkitx/artoolkitx-master/Source/ARX/ARVideo/Video4Linux2/videoV4L2.c:453:36: error: ‘V4L2_PIX_FMT_ARGB32’ undeclared (first use in this function)
                     vid->palette = V4L2_PIX_FMT_ARGB32;
                                    ^
It seems that V4L library may not be found. But I have already installed it. No idea how to fix. Thank you for your help.

**Comment by philip-lamb** [comment]
Ubuntu14.04 is really old. Is there any particular reason why you can't use a newer distro?

What is the output of `dpkg-query -l 'libv4l-dev'`

**Comment by Learningm** [comment]
> Ubuntu14.04 is really old. Is there any particular reason why you can't use a newer distro?
> 
> What is the output of `dpkg-query -l 'libv4l-dev'`

The development of our group are all Ubuntu14.04. 

I finally solved this problem by replacing some linux system header file containg the V4L2_XXX definition. I think the reason caused the above problem mainly due to old version of operating system.

I just want to test on linux platform and my target platform is Android. However, building the source code for Android platform outputs the .aar file. I have no idea how to use .aar in Unity, Would you have a plan to release a NDK .so file so that we can use the C/C++ API on mobile platform?

**Comment by philip-lamb** [comment]
This already gets built as part of the process.

Take a look in `Source/ARXJ/ARXJProj/arxj/build/intermediates/cmake/release/obj/` to find libARX.so for each built ABI.

Closing this issue now.
