### ISSUE TITLE
Problems with forum

### ISSUE THREAD

**Issue by pacocastamar** [artoolkitx/artoolkitx#55]
Hi,

I was following the progress of artoolkitx, because i'm planning to use it for a particular project, so I tried to post a couple of questions at the forum, but I noticed a lot of spam on it. 

I'm troubled with the fact that artoolkitx might be agonizing... Is it the case?

Sorry for using github for this question, but the forum doesn't seem reliable to do anything useful on it.

Regards

**Comment by ThorstenBux** [comment]
ArtoolkitX is maintained by the community. But you are right the forum isn’t very well looked after.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
