### ISSUE TITLE
Benchmarks information

### ISSUE THREAD

**Issue by robertinonicolazzi** [artoolkitx/artoolkitx#56]
Hello friend, sorry to post this question here, If is innappropiate you can delete. Im doing a final wokr with artoolkitx but i cant find any information about benchmark

is there some info about compare to another tools or about spped or accuracy?

Bye bye, and thanks a lot for what you are doing

**Comment by ThorstenBux** [comment]
This is the only benchmark I know of. http://augmentmy.world/js-artoolkit-performance
And it is focused on jsartoolkit!

**Comment by philip-lamb** [comment]
I'm not aware of any benchmarking that includes artoolkitX. There have been a number of academic papers in the past that have included ARToolKit in comparisons, but nothing recently that I'm aware of.
