### ISSUE TITLE
Can't build on Windows due to pthread.h not being found

### ISSUE THREAD

**Issue by GilbertoGojira** [artoolkitx/artoolkitx#58]
Hello i'm trying to build artoolkitx on windows without success. I've managed to do so in MacOS without problems.
I get a complaint about 'pthread.h' not being found.
Here is my CMake error file
[CMakeError.log](https://github.com/artoolkitx/artoolkitx/files/2411670/CMakeError.log)

**Comment by philip-lamb** [comment]
pthread.h is supplied with artoolkitX. The build works fine under tests.

If you're still experiencing this issue, please re-open and post a full build log.
