### ISSUE TITLE
Can't build artoolkitx on Android platform

### ISSUE THREAD

**Issue by GilbertoGojira** [artoolkitx/artoolkitx#59]
I'm trying to build artoolkitx for android on a Windows machine and it keeps failing.
My setup is:
Windows 10
Cygwin
Android SDK 21
Andoird NDK r13b
I also have similar problem building for android on MacOs
I've attached the output of issuing **./gradlew -q assembleRelease --info**
[build_info.log](https://github.com/artoolkitx/artoolkitx/files/2428903/build_info.log)

**Comment by philip-lamb** [comment]
Your NDK is too old. As noted in the Quick Start (https://github.com/artoolkitx/artoolkitx/blob/master/Quick%20start.md) NDK v16 or later is required.
