### ISSUE TITLE
NFT - Imageset

### ISSUE THREAD

**Issue by dy-dev** [artoolkitx/artoolkitx#6]
Hello

I'm trying to use the artoolkitx_2d_tracking_example and adapt it to use it as a nftmarker example (since I don't find the OCVT package I cannot use the example with a 2DTracker).
The issue I encounter is that the nfttracker, when creating new trackable and loading it from the pinball.jpg file, calls the ar2ReadSurfaceSet function, which in turns calls ar2ReadImageSet (in the  in the imagetSet.c file) where it tries to open "pinball.jpg.iset" which does not exist and I do not know what it the ".iset" extension is meant for.

I hope I am clear enough if you need me to clarify anything please let me know.

Any help would be appreciated because googling on the iset extension did not help a lot :(

Thank you

**Comment by philip-lamb** [comment]
The older NFT marker type (from ARToolKit v5.x) requires the jpeg to be pre-processed with the genTexData tool. After that is done, you supply just the name of the dataset without any file extension in the marker load.

**Comment by dy-dev** [comment]
thank you, I just found that out I should have looked at it 5 more minutes. Sorry ;)
