### ISSUE TITLE
Problems with cmake

### ISSUE THREAD

**Issue by shenjackson** [artoolkitx/artoolkitx#65]
I have meet the problem like this

-- Detecting C compile features - done
-- Using single-configuration CMake generator.
-- Found OpenCV: /usr/local/lib64/libopencv_calib3d.so;/usr/local/lib64/libopencv_features2d.so;/usr/local/lib64/libopencv_flann.so;/usr/local/lib64/libopencv_highgui.so;/usr/local/lib64/libopencv_videoio.so;/usr/local/lib64/libopencv_imgcodecs.so;/usr/local/lib64/libopencv_video.so;/usr/local/lib64/libopencv_imgproc.so;/usr/local/lib64/libopencv_core.so  
-- Defined: ARX_TARGET_PLATFORM_LINUX=1
-- Found JPEG: /usr/lib64/libjpeg.so  
-- Found OpenGL: /usr/lib64/libGL.so  
-- Found OpenGLES2: /usr/include
/usr/usr/local/opt/local
-- Found OpenGL3: GL  
-- Opting for desktop OpenGL. Set ARX_GL_PREFER_EMBEDDED to change.
-- Found GTSAM: /run/media/shen/D0CAFE99CAFE7B54/Opencv/7_AR/1_AR_toolkitx/thirdpartly/gtsam/install/lib/libgtsam.so  
-- Found CURL: /usr/lib64/libcurl.so (found version "7.29.0") 
/usr/lib64/libcurl.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1") 
-- Checking for one of the modules 'libudev'
-- Checking for one of the modules 'libdc1394-2'
-- Checking for one of the modules 'gstreamer-1.0'
**CMake Error at /usr/local/share/cmake-3.8/Modules/FindPkgConfig.cmake:641 (message):
  None of the required 'gstreamer-1.0' found**
Call Stack (most recent call first):
  ARX/ARVideo/GStreamer/CMakeLists.txt:2 (pkg_search_module)

-- Checking for one of the modules 'glib-2.0'
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Found OpenGLES2: /usr/include
/usr/usr/local/opt/local
<FindSDL2.cmake>
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
</FindSDL2.cmake>
-- Found SDL2: /run/media/shen/D0CAFE99CAFE7B54/Opencv/7_AR/1_AR_toolkitx/thirdpartly/SDL2-2.0.9/install/lib/libSDL2main.a;/run/media/shen/D0CAFE99CAFE7B54/Opencv/7_AR/1_AR_toolkitx/thirdpartly/SDL2-2.0.9/install/lib/libSDL2.so;-lpthread  
<FindSDL2.cmake>
</FindSDL2.cmake>
<FindSDL2.cmake>
</FindSDL2.cmake>
CMAKE_SOURCE_DIR /run/media/shen/D0CAFE99CAFE7B54/Opencv/7_AR/1_AR_toolkitx/Source
<FindSDL2.cmake>
</FindSDL2.cmake>
-- Configuring incomplete, errors occurred!

**Comment by philip-lamb** [comment]
sudo apt-get install gstreamer-1.0

**Comment by LinearPi** [comment]
help .how deal with in macOS . i want build android in macOS.   I built successfully on the window system.  when I build android in macOS, this bug I cannot deal  .Can you help me?

**Comment by philip-lamb** [comment]
@LinearPi You've commented on a closed issue which relates to neither Android nor macOS. Please open a new issue and give specific errors or problems you are encountering.
