### ISSUE TITLE
Displaying video on Android device

### ISSUE THREAD

**Issue by ebruekurnaz** [artoolkitx/artoolkitx#68]
I can't find any documentation about displaying video in artoolkitx, I tried ARMovieProj in artoolkit5 but it can't compile. Can you help me, are there any example projects or resource about displaying video with artoolkitx ?

**Comment by Lossdota** [comment]
I would also like to know if that feature excists

**Comment by philip-lamb** [comment]
At present, it's not a function provided by artoolkitX on Android unfortunately. On Android, we're still using Java Camera/Camera2 video grabbing, whereas on other platforms we're reusing the native video library to read video from file (i.e. using libARvideo).

You might find a workable solution using ffmpeg's Java bindings, but that is outside the scope of artoolkitX.
