### ISSUE TITLE
ARToolKit unable to properly display my webcam. #help wanted

### ISSUE THREAD

**Issue by lRaulMN7** [artoolkitx/artoolkitx#73]
![image](https://user-images.githubusercontent.com/39067731/50670318-211f7c00-0fcb-11e9-916b-36eed5422d0c.png)

I'm getting this issue when running ARToolKit. I tried with different webcams and all of them work on other apps like guvcview .
I spent 3 hours trying things but I can't find the solution... any ideas?
Note: I'm working on Ubuntu 16.04 (running in VirtualBox 5.2.20)

**Comment by kalwalt** [comment]
Are you using [Artoolkit5](https://github.com/artoolkitx/artoolkit5) or [ArtoolkitX](https://github.com/artoolkitx/artoolkitx)? If you are using Artoolkit5 there is a similar issue here https://github.com/artoolkitx/artoolkit5/issues/173
