### ISSUE TITLE
window10 VS17 Error initializing display of video frames from source

### ISSUE THREAD

**Issue by 258327199** [artoolkitx/artoolkitx#74]
Log:
[info] Created OpenGL 3.2+ context.
[info] artoolkitX v1.0.5 initalised.
[info] Loading image data G:\Git\artoolkitx\Examples\2d tracking example\Windows\build-windows\Release/pinball.jpg.
[info] First 2D marker trackable added; enabling 2D marker tracker.
[info] Added trackable (UID=0), total trackables loaded: 1.
[info] Starting...
[info] Setting video configuration '-module=WinMF -format=BGRA'.
[info] Opening artoolkitX video using configuration '-module=WinMF -format=BGRA'.
[info] Using supplied video config "-module=WinMF -format=BGRA".
[info] Using supplied video config "-module=WinMF -format=BGRA".
[info] Requesting images in BGRA format.
[info] Video 640x480 (AR_PIXEL_FORMAT_BGRA), rowBytes=2560.
[info] Opened artoolkitX video 640x480@4Bpp (AR_PIXEL_FORMAT_BGRA).
[warning] Using default camera parameters for 640x480 image size, 45 degrees vertical field-of-view.
[info] arVideoLuma will use Intel SIMD acceleration.
[info] Loading 2D data.
[ INFO:0] Initialize OpenCL runtime...
Marker Added
[info] 'G:\Git\artoolkitx\Examples\2d tracking example\Windows\build-windows\Release/pinball.jpg' assigned page no. 0.
[info] Loading of 2D data complete.
[error] Error: a required OpenGL function counld not be bound.
[error] Error initializing display of video frames from source.
[error] Unable to init ARVideoView.
[error] Error in ARController::drawVideoSettings().
[info] Closing artoolkitX video.
[info] Removed all 1 trackables.
[info] artoolkitX finished.
[info] artoolkitX finished.

video device:
Logitech  C1000e

**Comment by philip-lamb** [comment]
Possibly in arglOpenGLVersion.

**Comment by Rikdeleeuw** [comment]
I've had the same problem, in arg_gl3.c OpenGL functions are bound using wglGetProcAddress, however functions defined in opengl32.dll where not found by this function. Adding a function with a fallback to GetProcAddress solved it for me.

**Comment by kvibert** [comment]
> 
> 
> Possibly in arglOpenGLVersion.
 What can I do to fix it?

**Comment by philip-lamb** [comment]
Fixed in #98
