### ISSUE TITLE
 forum not usable, bots with spam

### ISSUE THREAD

**Issue by WhiteBit** [artoolkitx/artoolkitx#76]
Hello everyone, I realized that the forum is not usable, it seems to have been attacked by some hackers. Does anyone have more information?

**Comment by JuanCarlosGallo** [comment]
Hello @WhiteBit 

It is correct the forum (http://forums.artoolkitx.org/index.php) does not work and the website (http://www.hitl.washington.edu/artoolkit/) is down. The only place with help is http://www.artoolkitx.org/artoolkitx/Documentation/APIReference/ARX/html/index.html

I found this bloc https://so.csdn.net/so/search/s.do?q=artoolkit&t=blog&u=   it has been help for me 

Do you have any information about the instalation the artoolkitx or artoolkit 5?

Thanks

**Comment by JuanCarlosGallo** [comment]
@ThorstenBuxit is a great idea I would appreciate it if you help me with tutorials about the installation in ubuntu 16.04

thanks

**Comment by philip-lamb** [comment]
OK, other things have intervened and the forum got really bombed with spam. I've spent some time doing a cleanup and update but we have lost quite a few posts. In any case, it's back up now and should be usable.
