### ISSUE TITLE
I can not finish the installation of artoolkitx in ubuntu 16:04 

### ISSUE THREAD

**Issue by JuanCarlosGallo** [artoolkitx/artoolkitx#77]
Hello

I have problems with the installation of artoolkitx, and I did the following:

Download the following packages and install them with the command ` sudo dpkg -i name_packague.deb`
artoolkitx-lib_1.0.5.1_amd64.deb
artoolkitx-dev_1.0.5.1_amd64.deb
artoolkitx-examples_1.0.5.1_amd64.deb
artoolkitx-utils_1.0.5.1_amd64.deb
artoolkitx_1.0.5.1_amd64.deb

Then download the artoolkitx-master.zip SDK from https://github.com/artoolkitx/artoolkitx,
unzip with `unzip artoolkit-master.zip`
I went to the folder` ~ / Downloads / artoolkitx-master / Source $`
and run the following command` ./build.sh linux examples`

in the terminal the following appears

Downloading prebuilt OpenCV
-- Using single-configuration CMake generator.
-- Found OpenCV: /home/juanc/Descargas/artoolkitx-master/Source/depends/linux/lib/libopencv_calib3d.so;/home/juanc/Descargas/artoolkitx-master/Source/depends/linux/lib/libopencv_features2d.so;/home/juanc/Descargas/artoolkitx-master/Source/depends/linux/lib/libopencv_flann.so;/home/juanc/Descargas/artoolkitx-master/Source/depends/linux/lib/libopencv_highgui.so;/home/juanc/Descargas/artoolkitx-master/Source/depends/linux/lib/libopencv_videoio.so;/home/juanc/Descargas/artoolkitx-master/Source/depends/linux/lib/libopencv_imgcodecs.so;/home/juanc/Descargas/artoolkitx-master/Source/depends/linux/lib/libopencv_video.so;/home/juanc/Descargas/artoolkitx-master/Source/depends/linux/lib/libopencv_imgproc.so;/home/juanc/Descargas/artoolkitx-master/Source/depends/linux/lib/libopencv_core.so  
-- Defined: ARX_TARGET_PLATFORM_LINUX=1
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so  
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found OpenGLES2: /usr/include
/usr/usr/local/opt/local
-- Found OpenGL3: GL  
-- Opting for desktop OpenGL. Set ARX_GL_PREFER_EMBEDDED to change.
CMake Warning at ARX/CMakeLists.txt:80 (find_package):
  By not providing "FindGTSAM.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "GTSAM", but
  CMake did not find one.

  Could not find a package configuration file provided by "GTSAM" with any of
  the following names:

    GTSAMConfig.cmake
    gtsam-config.cmake

  Add the installation prefix of "GTSAM" to CMAKE_PREFIX_PATH or set
  "GTSAM_DIR" to a directory containing one of the above files.  If "GTSAM"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.47.0") 
/usr/lib/x86_64-linux-gnu/libcurl.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for one of the modules 'libudev'
-- Checking for one of the modules 'libdc1394-2'
-- Checking for one of the modules 'gstreamer-1.0'
-- Checking for one of the modules 'glib-2.0'
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found OpenGLES2: /usr/include
/usr/usr/local/opt/local
<FindSDL2.cmake>
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
</FindSDL2.cmake>
-- Found SDL2: /usr/lib/x86_64-linux-gnu/libSDL2main.a;/usr/lib/x86_64-linux-gnu/libSDL2.so;-lpthread  
<FindSDL2.cmake>
</FindSDL2.cmake>
<FindSDL2.cmake>
</FindSDL2.cmake>
CMAKE_SOURCE_DIR /home/juanc/Descargas/artoolkitx-master/Source
<FindSDL2.cmake>
</FindSDL2.cmake>
-- Configuring done
-- Generating done
-- Build files have been written to: /home/juanc/Descargas/artoolkitx-master/Source/build-linux-x86_64
[  7%] Built target ARUtil
[ 15%] Built target AR2
[ 19%] Built target OCVT
[ 53%] Built target AR
[ 62%] Built target Eden
[ 71%] Built target KPM
[ 74%] Built target ARG
[ 81%] Built target ARVideo
[ 90%] Built target ARX
[ 92%] Built target artoolkitx_check_id
[ 93%] Built target artoolkitx_genMarkerSet
[ 95%] Built target artoolkitx_mk_patt
[ 96%] Built target artoolkitx_checkResolution
[ 97%] Built target artoolkitx_image_database2d
[100%] Built target artoolkitx_genTexData
[100%] Built target artoolkitx_dispTexData
make: *** No hay ninguna regla para construir el objetivo 'install/strip'.  Alto.

I do not know what to do to finish the installation, I appreciate your help

**Comment by kalwalt** [comment]
hi @JuanCarlosGallo did you solved? have you installed all the dipendences as listed here: https://github.com/artoolkitx/artoolkitx/wiki/Building-artoolkitX-prerequisites#linux ? it seems that the lib was built but not installed, maybe you need run the build process with sudo command  e.g. ` sudo make` ?

**Comment by JuanCarlosGallo** [comment]
Hello

Verify and all the dependencies are installed and execute all the commands that you see in https://github.com/artoolkitx/artoolkitx/wiki/Building-artoolkitX-prerequisites#linux

Run `./build.sh linux examples` in the folder `~ / Downloads / artoolkitx-master / Source`  but the same thing appears in the terminal

I still can not execute the examples that artoolkitx brings, you know how to do it? Thank you

**Comment by kalwalt** [comment]
Hi @JuanCarlosGallo i did in the past, I remember that was a bit difficult to build, though i don't remember now what was fundamental. (missing lib or a different lib version). I will check and will let you know. I also build the Android version and i remember i have to copy some source code to build the project. I think not all te steps are listed. Sorry to not help so much...

**Comment by Asalle** [comment]
@JuanCarlosGallo you could also clone and install this GTSAM lib (https://bitbucket.org/gtborg/gtsam/)
and try to run the `build.sh` script again and see what happens.

**Comment by philip-lamb** [comment]
GTSAM is optional and the error is not caused by it not being present.. rather its some weird bug in cmake with makefiles that means that under some circumstances, the `install/strip` target isn't generated.

From memory, the solution is to do a manual `make` in the build directory and then run again.

**Comment by kalwalt** [comment]
Hi to all, @JuanCarlosGallo @philip-lamb  recently i tried to build the lib;  the problem is that you need to install additional libs not listed in the wiki:
`sudo apt install libcurl4-openssl-dev libssl-dev libsdl2-dev libdc1394-22-dev libgstreamer1.0-dev libsqlite3-dev`

This under Ubuntu 18.04, maybe other libs are needed. I will re-check this...

**Comment by kalwalt** [comment]
i built ArtoolkitX recently under Ubuntu 18.04 and i can comfirm my previous comment plus, it's needed to install libjasper as explained in this [article](https://researchxuyc.wordpress.com/2018/09/26/install-libjasper-in-ubuntu-18-04/) 

```shell
sudo add-apt-repository 'deb http://security.ubuntu.com/ubuntu xenial-security main'
sudo apt update
sudo apt install libjasper1 libjasper-dev
```
and manually libpng12 (because not in the Ubuntu 18.04) https://packages.ubuntu.com/xenial/libpng12-0

**Comment by philip-lamb** [comment]
Current build has a better list of dependencies.
