### ISSUE TITLE
Status of artoolkitx

### ISSUE THREAD

**Issue by ShadowMitia** [artoolkitx/artoolkitx#78]
What's the status of this project? Is it abandoned? On hold?

Any kind of information would be nice.

Thanks

**Comment by philip-lamb** [comment]
It's not abandoned... but the development are all pretty fully engaged on other projects, so our ability to help users is limited. Well organised patches are likely to be able to be accepted though.

**Comment by ShadowMitia** [comment]
Good to hear ! Thank you !
