### ISSUE TITLE
Nft crashing on Linux

### ISSUE THREAD

**Issue by martial** [artoolkitx/artoolkitx#79]
Hi,

nftSimple seems to be crashing on Linux ( Ubuntu 18 ).
I've been trying all versions 5.2, 5.3, 5.4 and artoolkitx fork and the issue is always the same.

On Mac OS everything is running perfectly fine.

Has anyone encountered this problem ?

**Comment by philip-lamb** [comment]
Duplicate of https://github.com/artoolkitx/artoolkitx/issues/118
