### ISSUE TITLE
2D markers not loading images in Android

### ISSUE THREAD

**Issue by SCornu** [artoolkitx/artoolkitx#81]
I have a problem with the function of 2d markers, I try to load other images to test the application and it gives me the following message per terminal:

I/libAR: [info] Loading image data Data/pi.jpg.
    [info] Unable to load image 'Data/pi.jpg'.
E/libAR: [error] Error: Failed to load trackable.
E/FrameListenerImpl: firstFrame(): Error configuring scene. Cannot continue.
E/libAR: [error] ARController::androidVideoPush2: ARVideoSource is not running.

I append the code that I have been using:

package com.ito.prueba2d2;

import android.opengl.GLES20;
import android.util.Log;

import org.artoolkitx.arx.arxj.ARController;
import org.artoolkitx.arx.arxj.Trackable;
import org.artoolkitx.arx.arxj.rendering.ARRenderer;
import org.artoolkitx.arx.arxj.rendering.shader_impl.Cube;
import org.artoolkitx.arx.arxj.rendering.shader_impl.SimpleFragmentShader;
import org.artoolkitx.arx.arxj.rendering.shader_impl.SimpleShaderProgram;
import org.artoolkitx.arx.arxj.rendering.shader_impl.SimpleVertexShader;

import javax.microedition.khronos.egl.EGLConfig;
import javax.microedition.khronos.opengles.GL10;

public class AR2dTrackingRenderer extends ARRenderer {

    private SimpleShaderProgram shaderProgram;

    private static final Trackable trackables[] = new Trackable[]{
            new Trackable("pinball.jpg", 1.0f),
            new Trackable("pi.jpg", 1.0f),
            new Trackable("pi2.jpg", 1.0f)
    };

    private int trackableUIDs[] = new int[trackables.length];

    private Cube cube;

    /**
     * Markers can be configured here.
     */
    @Override
    public boolean configureARScene() {

        int i = 0;

        for (Trackable trackable : trackables) {

            trackableUIDs[i] = ARController.getInstance().addTrackable("2d;Data/" + trackable.getName() + ";" + trackable.getWidth());

            //trackableUIDs[i] = i;

            if (trackableUIDs[i] < 0) return false;
            i++;
        }
        return true;
    }

    //Shader calls should be within a GL thread. GL threads are onSurfaceChanged(), onSurfaceCreated() or onDrawFrame()
    //As the cube instantiates the shader during setShaderProgram call we need to create the cube here.
    @Override
    public void onSurfaceCreated(GL10 unused, EGLConfig config) {
        this.shaderProgram = new SimpleShaderProgram(new SimpleVertexShader(), new SimpleFragmentShader());
        cube = new Cube(100.0f, 50.0f, 50.0f, 40.0f);
        cube.setShaderProgram(shaderProgram);
        super.onSurfaceCreated(unused, config);
    }

    /**
     * Override the draw function from ARRenderer.
     */
    @Override
    public void draw() {
        super.draw();

        GLES20.glEnable(GLES20.GL_CULL_FACE);
        GLES20.glEnable(GLES20.GL_DEPTH_TEST);
        GLES20.glFrontFace(GLES20.GL_CCW);

        // Look for trackables, and draw on each found one.
        for (int trackableUID : trackableUIDs) {
            // If the trackable is visible, apply its transformation, and render a cube
            float[] modelViewMatrix = new float[16];
            if (ARController.getInstance().queryTrackableVisibilityAndTransformation(trackableUID, modelViewMatrix)) {
                float[] projectionMatrix = ARController.getInstance().getProjectionMatrix(10.0f, 10000.0f);
                cube.draw(projectionMatrix, modelViewMatrix);
            }
        }
    }
}

**Comment by mmahkamov** [comment]
There's a method that explains it all (I also spent a lot of time trying to understand why my image is not being loaded):

```
    protected fun initializeInstance() {
        // Unpack assets to cache directory so native library can read them.
        // N.B.: If contents of assets folder changes, be sure to increment the
        // versionCode integer in the modules build.gradle file.
        val assetHelper = AssetHelper(assets)
        assetHelper.cacheAssetFolder(this, "Data")
        assetHelper.cacheAssetFolder(this, "cparam_cache")
    }
```

Basically, your assets are copied once to the cache directory. They're not refreshed until you change versionCode.

**Comment by philip-lamb** [comment]
You can also use the "clear cache" button on the app's settings in Android settings. Uninstalling the app also clears the cache.
