### ISSUE TITLE
Please upload Android-unity.zip (1.0.5.1)

### ISSUE THREAD

**Issue by mironal** [artoolkitx/artoolkitx#90]
I tried to building [arunityx](https://github.com/artoolkitx/arunityx) for android. 

But I got a not found error. 

I think may be forgot upload Android-unity.zip.

![image](https://user-images.githubusercontent.com/537587/61946667-2af7e380-afde-11e9-8311-074605ab3267.png)

**Comment by philip-lamb** [comment]
The problem here is that we're using a free tier on the CI system, and building the Android Unity plugin exceeds the free tier time-limit, so it doesn't get built. If we can get a project sponsor who is willing to fund the CI system (~ USD 1k/per year) this will be addressed.
