### ISSUE TITLE
Example using arVideoOpen

### ISSUE THREAD

**Issue by huyhoangk50** [artoolkitx/artoolkitx#93]
Do we have examples using arVideoOpen and arDetectMakers to arDetectMarker. Just like simpleLite example in artoolkit5. Thank you.

**Comment by philip-lamb** [comment]
There aren't any examples using arVideoOpen or ar2VideoOpen directly any more (as using ARVideoSource instead saved a lot of boilerplate code), but the check_id utility uses arDetectMarker directly, so it's probably closest to the original simpleLite ARToolKit v5 example.

If you wanted to revert to directly opening the video source yourself, you could pretty-much copy and past the setup code from an ARToolKit v5 example, and it should work. Note that you won't get the automated handling of camera parameters that ARVideoSource does for you now.
