### ISSUE TITLE
Looking for people to work together

### ISSUE THREAD

**Issue by ghost** [artoolkitx/artoolkitx#94]
Hey guys,

i'm looking for some people that want to work together.
I'm new to developing with artoolkitx and would appreciate if I could ask people if I have a 
concrete question about a problem.
But if you're also new to AR-Programming then text back so we can learn together.

fauxKenji

**Comment by ThorstenBux** [comment]
I started to setup a community here https://www.facebook.com/groups/2265208223759741/?source_id=354952125342920 feel free to join and ask questions :)
