### ISSUE TITLE
AMD64 Android Libraries / Unity Version Not Available

### ISSUE THREAD

**Issue by OptrixAU** [artoolkitx/artoolkitx#96]
I've noticed that Unity versions appear to be available for iOS, Windows and MacOS, but nothing for Android.

There are also no AMD64 libraries available for Android either, which of course means that you can't publish anything through the Google Play Store, since they now _require_ 64-bit native content. 

Is there any status on this? Is there anything I can do to help get it working? We've based one of our products on ARToolkit v5, and now we find ourselves unable to update it because of the lack of 64-bit version - I had hoped there might have been some progress on ARToolkitX.

**Comment by philip-lamb** [comment]
artoolkitX for Android includes both ARM64 and x86_64 libraries and apks. Building the Unity libs is complicated by the need for a Unity license on the CI system, which is not something we've addressed, but you could do a local build. Best to file those issues in https://github.com/artoolkitx/arunityx/issues though.

**Comment by ThorstenBux** [comment]
Well, actually it looks like the build for unity is only adding X86 into the bundle.
https://github.com/artoolkitx/arunityx/blob/master/Source/build.sh#L110

**Comment by ThorstenBux** [comment]
Also, the release on the GitHub releases has stopped including Android starting with release 1.0.5. Prior to that Android-unity is still available. But only armeabi-v7a and x86. I think what @OptrixAU needs it arm64-v8a which is not part of the released libs

**Comment by OptrixAU** [comment]
I can see Android/libs/armeabi-v7a/libARX.so and Android/libs/x86/libARX.so - I believe these are the 32-bit ARM and the x86 libraries, there's nothing there showing ARM64. 

There hasn't been a 1.0.5 android-unity.zip. The newest is a 1.0.4 version, and its apparently again only 32-bit ARM and x86 - no 64-bit version. 

I'm trying to see if I can build my own version, but it's not currently building (seems to be having trouble finding the SDK, even though ANDROID_HOME is set). Interestingly, OpenCV2 does have ARM64 libraries, so I'm hopeful.

**Comment by OptrixAU** [comment]
Ahh, you beat me to it @ThorstenBux - my comment is pretty much yours over again :P.

Was the removal of the Android-Unity.zip file in recent releases deliberate?

**Comment by philip-lamb** [comment]
No, just an unfortunate consequence of the project being financially unsupported. The CI hit its monthly free-tier limit. Looking into this now.

**Comment by OptrixAU** [comment]
Sorry for this to suddenly be an issue - Android P introduced a new 'feature' that broke our application (you now can't connect to insecure websites via HTTP on Android unless you add a specific line to your manifest).

Unfortunately we can't update our app at the moment, because Google won't accept a new version without it including an ARM64 version. We've fallen back on distributing the app via APK, but it's of course happened with the worlds worst timing :P

If you'd like to message me with the amount you'd need to bump up to non-free tier for your integration, I can bring it up with management. We might be able to be a minor sponsor for the project.

**Comment by ThorstenBux** [comment]
[arm64-v8a.zip](https://github.com/artoolkitx/artoolkitx/files/3553705/arm64-v8a.zip)
that should be what you are looking for.
You would need to bundle the plugin still

**Comment by ThorstenBux** [comment]
As for packaging from the unity packaging script.
Looks like we would need to add the v8 libs here:
https://github.com/artoolkitx/arunityx/blob/master/Source/build.sh#L121

and update the path because my build now has the libs in a path like this:
```
Source/ARXJ/ARXJProj/arxj/build/intermediates/library_and_local_jars_jni/release/arm64-v8a
```

and not
```Source/ARXJ/ARXJProj/arxj/build/intermediates/bundles/release/jni```

**Comment by ThorstenBux** [comment]
@OptrixAU happy to review a PR :)

**Comment by OptrixAU** [comment]
@ThorstenBux - oh, and you're over in NZ! Howdy, neighbour. And THANK YOU for the library. Still struggling to build the thing, but it's mostly 'cause my NDK isn't downloading at the moment. 

I know this is off-topic, but I don't suppose there's a list of "Dos and Don'ts" when porting a project from ARToolkit5-Unity to ARUnityX? If I happen to simply rename the 'artoolkitX-unity' folder to 'artoolkit5-unity' and drop it into place, have I got a better-than-average chance of this thing working?

**Comment by OptrixAU** [comment]
Had a few issues on the Unity end, but that's for another project - https://github.com/artoolkitx/arunityx/issues/21

**Comment by philip-lamb** [comment]
Full arm64 libs now provided.
