### ISSUE TITLE
Windows Samples Not Working

### ISSUE THREAD

**Issue by OptrixAU** [artoolkitx/artoolkitx#97]
I was experiencing a crash in the Unity version of ARUnityX, but realised I had better check out the samples to make sure that the underlying ARToolkit was working. The samples do **not** work.

There are four [Error] lines below - it looks as if some part of the tool is trying to use OpenGL API functions that aren't present on my machine, or Windows machines generally. The system uses an GTX1060 video card, if that is relevant.

At the very least, is it possible to make the error messages state _which_ OpenGL API function is absent?

```
[info] Created OpenGL 3.2+ context.
[info] artoolkitX v1.0.5 initalised.
[info] Loading image data D:\OpenSource\Temp/pinball.jpg.
[info] First 2D marker trackable added; enabling 2D marker tracker.
[info] Added trackable (UID=0), total trackables loaded: 1.
[info] Starting...
[info] Setting video configuration '-module=WinMF -format=BGRA'.
[info] Opening artoolkitX video using configuration '-module=WinMF -format=BGRA'.
[info] Using supplied video config "-module=WinMF -format=BGRA".
[info] Using supplied video config "-module=WinMF -format=BGRA".
[info] Requesting images in BGRA format.
[info] Video 1280x720 (AR_PIXEL_FORMAT_BGRA), rowBytes=5120.
[info] Opened artoolkitX video 1280x720@4Bpp (AR_PIXEL_FORMAT_BGRA).
[warning] Using default camera parameters for 1280x720 image size, 45 degrees vertical field-of-view.
[info] arVideoLuma will use Intel SIMD acceleration.
[info] Loading 2D data.
Marker Added
[info] 'D:\OpenSource\Temp/pinball.jpg' assigned page no. 0.
[info] Loading of 2D data complete.
[error] Error: a required OpenGL function counld not be bound.
[error] Error initializing display of video frames from source.
[error] Unable to init ARVideoView.
[error] Error in ARController::drawVideoSettings().
[info] Closing artoolkitX video.
[info] Removed all 1 trackables.
[info] artoolkitX finished.
```

**Comment by OptrixAU** [comment]
Right now it's suspected as possibly being involved in https://github.com/artoolkitx/arunityx/issues/22 - although that's just a suspicion right now rather than proven.

**Comment by kalwalt** [comment]
It could be that the app try the find the OpenGL .dll libs, but It can't. You should read in the build log, in the initial part where cmake check which libs to use, if cmake fails to find OpenGL. I can not test It because i have only Linux on my PC.

**Comment by OptrixAU** [comment]
The log starts with "Created OpenGL 3.2+ context" - I've checked the code and it looks like it's already verified that the DLL is present and supports OpenGL 3.2.

**Comment by philip-lamb** [comment]
I don't have a windows system I can quickly test on, but try this branch and let me know if it solves the issue: https://github.com/artoolkitx/artoolkitx/tree/phil-windows-gl3

**Comment by OptrixAU** [comment]
Got the branch downloaded, I'll give it a try in the morning (I have the CMAKE tools installed, but for some reason they aren't working).

**Comment by OptrixAU** [comment]
Yes - Windows samples seem to be working on that branch. Camera turns on, camera texture appears and updates, app doesn't crash.

**Comment by philip-lamb** [comment]
OK, I have also tested on a Windows system and it looks like it addresses that particular issue. Merged now.
