### ISSUE TITLE
Crash In videoRGBA When Used On Windows Camera w/ No Format Options (AR_PIXEL_FORMAT_420)

### ISSUE THREAD

**Issue by OptrixAU** [artoolkitx/artoolkitx#99]
I had a regular crash when using getFrameTextureRGBA to get texture frame data. 

This ended up being due to the pixel format - it attempted to use AR_PIXEL_FORMAT_420.

While objects would **track** using this format - meaning that ARToolkit obviously could interpret the footage correctly - it seems that there may be a bug in the conversion of this pixel format to RGBA. Based on the errors I was getting, I'm guessing it's attempting to write outside the bounds of the memory buffer given.

While it would be certainly nice to be able to convert this without the crash, a temporary alternative might be to....

   a) Return NULL if you're using a pixel format of AR_PIXEL_FORMAT_420, or
   b) Automatically add a '-format BGRA' directive to the Windows camera connection string if there is no format directive already there, to help avoid this case.

**Comment by philip-lamb** [comment]
@OptrixAU What platform and version? I'd like to try to reproduce this.

**Comment by OptrixAU** [comment]
Windows 10, on the latest version of both ARToolkit and Windows available publicly at the time of posting.

It might be that if the pixel format was unspecified, it reverted to the default for my particular camera, so I'm not entirely sure you'll get the issue easily. It's easily remedied by forcing the format if it's not otherwise specified (which I've done internally in my application).

**Comment by philip-lamb** [comment]
`getFrameTextureRGBA` conversion is supposed to work for all pixel formats, and accelerated for `AR_PIXEL_FORMAT_420f` and `AR_PIXEL_FORMAT_NV21`, but looking at it now, it does seem that support for `AR_PIXEL_FORMAT_420v` was never implemented, although it seems unlikely that this was the source of the crash, as it's not a common video format at all (basically it was a video-range format used on the early iPhones). In any case, I've added an (unaccelerated) format conversion for this now in https://github.com/artoolkitx/artoolkitx/commit/fee2abef2273e9ae07ae939cb986f468222d134d.

**Comment by philip-lamb** [comment]
Well, I'll close this for now. If you can add a vconf that reproduces the error, please reopen and comment.
